name: codejit
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - scipy
  - gensim
  - tqdm
  - graphviz
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # or your specific CUDA version
  - pyg  # PyTorch Geometric

